function postMessageToDiscord(message) {

  message = message || "I pull up....";

  var discordUrl = 'https://discord.com/api/webhooks/845543471481880647/DEJS5OEj_RxhYu-PbS_Pdprq2QTskyQxQfEyIYOodlI1it-95J06o_j1U617fdngzTEb';
  var payload = JSON.stringify({content: message});

  var params = {
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded'
    },
    method: "POST",
    payload: payload,
    muteHttpExceptions: true
  };

  var response = UrlFetchApp.fetch(discordUrl, params);

  Logger.log(response.getContentText());

}

